// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"database/sql"
	"time"
)

type Permission struct {
	ID    int64
	Slug  *string
	Email *string
}

type Session struct {
	Token  string
	Data   []byte
	Expiry float64
}

type Text struct {
	ID        int64
	Title     string
	Content   string
	UserID    int64
	CreatedAt time.Time
}

type User struct {
	ID           int64
	GoogleUserID *string
	Name         *string
	Email        *string
}

type UserPermission struct {
	UserID       sql.NullInt64
	PermissionID sql.NullInt64
}

type UserWord struct {
	UserID int64
	WordID int64
	Status string
}

type Word struct {
	ID          int64
	Word        string
	Pos         string
	Definitions *string
}
