// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: texts.sql

package queries

import (
	"context"
	"time"
)

const addText = `-- name: AddText :exec
insert into texts (title, content, user_id, created_at) values (?, ?, ?, ?)
`

type AddTextParams struct {
	Title     string
	Content   string
	UserID    int64
	CreatedAt time.Time
}

func (q *Queries) AddText(ctx context.Context, arg AddTextParams) error {
	_, err := q.db.ExecContext(ctx, addText,
		arg.Title,
		arg.Content,
		arg.UserID,
		arg.CreatedAt,
	)
	return err
}

const allTextsWithoutContent = `-- name: AllTextsWithoutContent :many
select id, title, user_id, created_at from texts
`

type AllTextsWithoutContentRow struct {
	ID        int64
	Title     string
	UserID    int64
	CreatedAt time.Time
}

func (q *Queries) AllTextsWithoutContent(ctx context.Context) ([]AllTextsWithoutContentRow, error) {
	rows, err := q.db.QueryContext(ctx, allTextsWithoutContent)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AllTextsWithoutContentRow
	for rows.Next() {
		var i AllTextsWithoutContentRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getText = `-- name: GetText :one
select id, title, content, user_id, created_at from texts where id = ?
`

func (q *Queries) GetText(ctx context.Context, id int64) (Text, error) {
	row := q.db.QueryRowContext(ctx, getText, id)
	var i Text
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}
