// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: word.sql

package queries

import (
	"context"
)

const addWord = `-- name: AddWord :exec
insert or ignore into words (word, pos) values (?, ?)
`

type AddWordParams struct {
	Word string
	Pos  string
}

func (q *Queries) AddWord(ctx context.Context, arg AddWordParams) error {
	_, err := q.db.ExecContext(ctx, addWord, arg.Word, arg.Pos)
	return err
}

const getWordDefinition = `-- name: GetWordDefinition :one
select definitions from words where word = ? and pos = ?
`

type GetWordDefinitionParams struct {
	Word string
	Pos  string
}

func (q *Queries) GetWordDefinition(ctx context.Context, arg GetWordDefinitionParams) (*string, error) {
	row := q.db.QueryRowContext(ctx, getWordDefinition, arg.Word, arg.Pos)
	var definitions *string
	err := row.Scan(&definitions)
	return definitions, err
}

const updateWordDefinition = `-- name: UpdateWordDefinition :exec
update words set definitions = ? where word = ? and pos = ?
`

type UpdateWordDefinitionParams struct {
	Definitions *string
	Word        string
	Pos         string
}

func (q *Queries) UpdateWordDefinition(ctx context.Context, arg UpdateWordDefinitionParams) error {
	_, err := q.db.ExecContext(ctx, updateWordDefinition, arg.Definitions, arg.Word, arg.Pos)
	return err
}
