// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: word.sql

package queries

import (
	"context"
)

const addUserWord = `-- name: AddUserWord :exec
insert or ignore into user_words(user_id, word_id, status) select ? as user_id, id as word_id, ? as status from words where word = ? and pos = ?
`

type AddUserWordParams struct {
	UserID int64
	Status string
	Word   string
	Pos    string
}

func (q *Queries) AddUserWord(ctx context.Context, arg AddUserWordParams) error {
	_, err := q.db.ExecContext(ctx, addUserWord,
		arg.UserID,
		arg.Status,
		arg.Word,
		arg.Pos,
	)
	return err
}

const addWord = `-- name: AddWord :exec
insert or ignore into words (word, pos) values (?, ?)
`

type AddWordParams struct {
	Word string
	Pos  string
}

func (q *Queries) AddWord(ctx context.Context, arg AddWordParams) error {
	_, err := q.db.ExecContext(ctx, addWord, arg.Word, arg.Pos)
	return err
}

const getUserWords = `-- name: GetUserWords :many
select words.id, words.word, words.pos, words.definitions from user_words left join words on words.id = user_words.word_id where user_id = ?
`

type GetUserWordsRow struct {
	Word Word
}

func (q *Queries) GetUserWords(ctx context.Context, userID int64) ([]GetUserWordsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserWords, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserWordsRow
	for rows.Next() {
		var i GetUserWordsRow
		if err := rows.Scan(
			&i.Word.ID,
			&i.Word.Word,
			&i.Word.Pos,
			&i.Word.Definitions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWordDefinition = `-- name: GetWordDefinition :one
select definitions from words where word = ? and pos = ?
`

type GetWordDefinitionParams struct {
	Word string
	Pos  string
}

func (q *Queries) GetWordDefinition(ctx context.Context, arg GetWordDefinitionParams) (*string, error) {
	row := q.db.QueryRowContext(ctx, getWordDefinition, arg.Word, arg.Pos)
	var definitions *string
	err := row.Scan(&definitions)
	return definitions, err
}

const updateWordDefinition = `-- name: UpdateWordDefinition :exec
update words set definitions = ? where word = ? and pos = ?
`

type UpdateWordDefinitionParams struct {
	Definitions *string
	Word        string
	Pos         string
}

func (q *Queries) UpdateWordDefinition(ctx context.Context, arg UpdateWordDefinitionParams) error {
	_, err := q.db.ExecContext(ctx, updateWordDefinition, arg.Definitions, arg.Word, arg.Pos)
	return err
}
